# Generated by Django 5.2.5 on 2025-11-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogcategory_tag_blogpost_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='offerproduct',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Link this offer to a specific product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='core.product'),
        ),
        migrations.AlterField(
            model_name='offerproduct',
            name='image',
            field=models.ImageField(upload_to='offers/'),
        ),
    ]
