# Generated by Django 5.2.5 on 2025-11-28 11:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_offerproduct_price_offerproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full detailed description for product detail page', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Short description for product listings', verbose_name='Text'),
        ),
    ]
